export const MICROSERVICE = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  ACCOUNT_GUEST_SERVICE: 'ACCOUNT_GUEST_SERVICE',
  ACCOUNT_EMPLOYEE_SERVICE: 'ACCOUNT_EMPLOYEE_SERVICE',
  PAYMENT_SERVICE: 'PAYMENT_SERVICE',
  PRODUCT_SERVICE: 'PRODUCT_SERVICE',
  REDIS_SERVICE: 'REDIS_SERVICE',
};
