export const MICROSERVICE = {
  AUTH_SERVICE: 'AUTH_SERVICE',
  USER_SERVICE: 'USER_SERVICE',
  PAYMENT_SERVICE: 'PAYMENT_SERVICE',
  PRODUCT_SERVICE: 'PRODUCT_SERVICE',
  REDIS_SERVICE: 'REDIS_SERVICE',
};
