
import '@/utils/suppressAntdWarnings.early';
import '@ant-design/v5-patch-for-react-19';
import '@/utils/suppressAntdWarnings';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ToastContainer } from 'react-toastify';
import { QueryProvider } from '@/providers/QueryProvider';
// import { AuthEmployeeProvider } from '@/hooks/AuthEmployeeContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    { rel: 'icon', type: 'image/png', sizes: '32x32', url: '/laptop.png?v=2' },
    { rel: 'apple-touch-icon', url: '/laptop.png?v=2' },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

        <ToastContainer position='top-right'></ToastContainer>
        {/* <AuthEmployeeProvider> */}
        <QueryProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </QueryProvider>
        {/* </AuthEmployeeProvider> */}

      </body>
    </html>
  );
}
