// User Roles Constants
export const USER_ROLE = {
  GUEST: "guest",
  USER: "user",
  ADMIN: "admin",
  SUPER_ADMIN: "super_admin",
} as const;

export type UserRole = (typeof USER_ROLE)[keyof typeof USER_ROLE];

export const MICROSERVICE = {
  AUTH_SERVICE: "AUTH_SERVICE",
  PRODUCT_SERVICE: "PRODUCT_SERVICE",
  REDIS_SERVICE: "REDIS_SERVICE",
  HISTORY_LOG_SERVICE: "HISTORY_LOG_SERVICE",
  CART_SERVICE: "CART_SERVICE",
  PAYMENT_SERVICE: "PAYMENT_SERVICE",
  ORDER_SERVICE: "ORDER_SERVICE",
  NOTIFICATION_SERVICE: "NOTIFICATION_SERVICE",
} as const;

export type MicroserviceName = (typeof MICROSERVICE)[keyof typeof MICROSERVICE];

export const MICROSERVICE_PORT = {
  AUTH_SERVICE: 3001,
  PRODUCT_SERVICE: 3002,
  HISTORY_LOG_SERVICE: 3003,
  CART_SERVICE: 3004,
  PAYMENT_SERVICE: 3005,
  ORDER_SERVICE: 3006,
  NOTIFICATION_SERVICE: 3007,
} as const;

export type MicroservicePort =
  (typeof MICROSERVICE_PORT)[keyof typeof MICROSERVICE_PORT];
